name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bin/rails spec

      - name: Run RuboCop
        run: bin/rubocop

      - name: Run Brakeman
        run: bin/brakeman